name: ase_movies
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9.6
  - django=3.2.8
  - psycopg2==2.8.4
  - psycopg2-binary==2.9.3
  - pytest==6.2.5
  - pytest-sugar==0.9.4
  - pytest-django==4.1.0
  - black==20.8b1
  