# Generated by Django 3.2.8 on 2022-01-16 00:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('full_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('title', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('length', models.FloatField()),
                ('star_rating', models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('released_on', models.DateField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('trailer', models.URLField(blank=True, default=None, max_length=500)),
                ('plot', models.TextField()),
                ('actor', models.ManyToManyField(related_name='movie_actor', to='movies.Persona')),
                ('director', models.ManyToManyField(related_name='movie_director', to='movies.Persona')),
            ],
        ),
    ]
