# Generated by Django 3.2.8 on 2022-01-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('full_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='type',
            field=models.IntegerField(choices=[(0, 'Both'), (1, 'Actor'), (2, 'Director')], default=0),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='movie',
            name='star_rating',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='movie_genre', to='movies.Genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='star_rating',
            field=models.ManyToManyField(blank=True, related_name='assigned_by', to='movies.User'),
        ),
    ]
