# Generated by Django 3.2.8 on 2022-02-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_path',
            field=models.URLField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='length',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.URLField(blank=True, max_length=254, null=True),
        ),
    ]
