# Generated by Django 3.2.8 on 2022-01-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20220117_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('full_name', models.CharField(max_length=300, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='movie',
            name='star_rating',
            field=models.ManyToManyField(blank=True, related_name='assigned_by', to='movies.Viewer'),
        ),
    ]
