# Generated by Django 3.2.8 on 2022-02-10 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20220210_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='fav_genre',
        ),
    ]
