# Generated by Django 3.2.8 on 2022-02-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_userprofile_fav_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fav_genre',
            field=models.TextField(blank=True, null=True),
        ),
    ]
